# Generated by Django 4.2.24 on 2025-10-01 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="assigned_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_under_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
