# Generated by Django 4.2.24 on 2025-10-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_profile_assigned_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="assigned_admin",
        ),
    ]
