# Generated by Django 4.2.24 on 2025-10-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created_by",
        ),
    ]
