# Generated by Django 4.2.24 on 2025-10-01 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0006_remove_task_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
