# Generated by Django 4.2.24 on 2025-10-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_profile_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="manager",
        ),
    ]
